### ISSUE TITLE
Macht das Addon hier Sinn?

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/out5#11]
Hallo,

glaubt Ihr das Addon ist (hier) sinnvoll?

Ich finde die paar Funktionen die es jetzt schon als Plugins gibt sehr nützlich.
Können die Funktionen einfacher als in Plugins gelöst werden (siehe XOutPutFilter (Rex4) von Andreas).

Können die hier vorhandenen Plugin evtl. besser in einem anderen Addon eingebaut werden (z.B.  Peters Mutter Addon https://github.com/FriendsOfREDAXO/wuensche_ideen/issues/8)

LG
Oliver

**Comment by polarpixel** [comment]
Ich finde: ja!

**Comment by schuer** [comment]
Ich fände alle Plugins als eigenständige **Addons** schöner. Finde sie in ihrer aktuellen Form als Plugins thematisch etwas wirr.

Aber das ist nur mein persönlicher Geschmack. Weil du gefragt hast :)

**Comment by olien** [comment]
Danke. Wollte irgendwie die Anzahl der Addons nicht künstlich hochschrauben für "Kleinigkeiten" :-)
Vielleicht kommen ja noch Ideen...

**Comment by skerbis** [comment]
Ich würde es nicht als X verschiedene Addons veröffentlicht sehen wollen. Die Idee mit dem Mutter-Addon finde ich gut.

**Comment by olien** [comment]
Ich möchte hier nochmal anregend as AddOn rauszunehmen (auch aus dem Installer).
Es gibt wirklich alles was das AddOn liefert inzwischen in anderen AddOns. Skerbis würde sich evtl. den Wartungsmodus schnappen und draus ein eigenständiges AddOn bauen...

Was sagt Ihr? Weg mit dem alten Kram?

**Comment by schuer** [comment]
Ich würde es aus dem Installer rausnehmen, damit es zukünftig nicht weiter installiert wird. Aber ich würde es _nicht_ bei GitHub löschen. Dort sollten Dinge eigentlich dauerhaft bleiben, falls sie nochmal benötigt werden. Ich würde lediglich gut sichtbar drüber schreiben, dass das Addon deprecated ist und nicht mehr weiterentwickelt wird, und wo sich die Alternativen befinden.

Falls Skerbis es als Maintenance-Addon umbaut, sollten wir vermutlich besser ein frisches Repo dafür anlegen.

**Comment by olien** [comment]
OK.

**Comment by skerbis** [comment]
ok nimm's raus aus dem Installer. Das Maintenance-AddOn kommt am WE
