### ISSUE TITLE
Funktionsweise erläutern / ausbauen?

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/out5#16]
Hi!

Ich hatte erwartet, dass out5 ähnlich funktioniert zum xOutputFilter und man eigene Filter für Frontend und Backend aus dem Redaxo-Backend anlegen kann. Wie ist das in Zukunft geplant? Muss man wirklich für jede Ersetzung ein eigenes Plugin installieren?

Bin gespannt auf die Entwicklung!

**Comment by olien** [comment]
Siehe https://github.com/FriendsOfREDAXO/out5/issues/17
