### ISSUE TITLE
Name im Menü

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/out5#17]
![image](https://cloud.githubusercontent.com/assets/3855487/15799122/8dc3bd28-2a52-11e6-8699-2354d7a88e9e.png)

Hier würde ich mir wünschen, dass analog zu anderen Addons ein aussagekräftiger Name in Großbuchstaben gewählt wird. Sowas wie "Ersetzungen" oder eben zumindest "Output-Filter".

**Comment by olien** [comment]
Hallo Alex,

ich habe Andreas Eberhard überreden können sein XOutPutfilter Addon für Rex5 neu zu entwicklen.
Da ich ihn drängeln werde die Möglichkeiten aus out5 zu übernehmen und das Addon um längen flexibler als das out5 werden wird werde ich hier aktuell nicht viel Zeit für Änderungen investieren.

LG
Oliver
