### ISSUE TITLE
Out5 produziert Leerzeichen bei der Ausgabe

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/out5#19]
Mir ist aufgefallen, dass R5 anscheinend am Anfang immer 2 leerzeichen macht. Auch wenn im Template direkt REX_ARTICLE[] an erster stelle steht? habe das problem, dass mein XML-Feed wegen der 2 Zeichen am Anfang ungültig ist. aber keine Ahnung, woher sie kommen. Als ich out5 deaktiviert habe, ging es wieder. 
Das min addon war übrigens deaktiviert. In dem Zusammenhang habe ich mich auch gefragt, ob sich out5 ggf für einzelne Artikel (wie zB RSS-Feeds) deaktivieren lässt?
Zudem habe ich nicht verstanden, wie sich der Structure Separator verwenden lässt. Vielleicht noch einen Hilfetext wert. (offtopic)

**Comment by olien** [comment]
Hallo Stefan,
Das mit den Leerzeichen kommt aus dem Structure Separator Plugin und ist hier in der github Version schon behoben.

Wie das genutzt werden kann erkläre ich dir später. Wobei wir nochmal diskutieren muss ob wir out5 behalten.

Alles was out5 kann gibt es inzwischen in anderen AddOns. 

LG
Oliver

**Comment by dpf-dd** [comment]
Hmm, interessant. In welchem anderen AddOn gibt es den Kategorie-Seperator fürs Backend? :D

**Comment by olien** [comment]
https://github.com/FriendsOfREDAXO/structure_tweaks
