### ISSUE TITLE
Wunsch: Border festtackern

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/out5#21]
Der Border am oberen Rand sollte auch nach dem Scrollen sichtbar sein.

**Comment by skerbis** [comment]
Vielleicht als Option?

**Comment by marcohanke** [comment]
Gerne auch als Option.
Ich muss immer mal wieder zwischen dev und live hin und her springen, dafür wäre es sehr cool.

**Comment by olien** [comment]
Ok. Kann ich mir angucken wobei ich es sinnvoller finde das Aden nicht mehr zu verwenden sondern die Dinge die noch "nur" von Out5 zur verfügung gestellt werden in das Theme oder Project Addon zu packen...

**Comment by skerbis** [comment]
Ich benutze nur noch das Login-Bild und Border beides ist eher dem Customizer-Plugin zuzuordnen - denke ich
